# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\ning\predictor\predictor_ui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(705, 562)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout.addWidget(self.textBrowser, 2, 0, 1, 2)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setProperty("value", 100)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 8, 0, 1, 2)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.gridLayout.addWidget(self.plainTextEdit, 1, 1, 1, 1)
        self.analyzeTab = QtWidgets.QTabWidget(self.centralwidget)
        self.analyzeTab.setObjectName("analyzeTab")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.analyzeLineEdit = QtWidgets.QLineEdit(self.tab)
        self.analyzeLineEdit.setObjectName("analyzeLineEdit")
        self.gridLayout_4.addWidget(self.analyzeLineEdit, 6, 0, 1, 1)
        self.computeButton = QtWidgets.QPushButton(self.tab)
        self.computeButton.setObjectName("computeButton")
        self.gridLayout_4.addWidget(self.computeButton, 6, 1, 1, 1)
        self.radioButton_4 = QtWidgets.QRadioButton(self.tab)
        self.radioButton_4.setObjectName("radioButton_4")
        self.gridLayout_4.addWidget(self.radioButton_4, 2, 0, 1, 1)
        self.avgButton = QtWidgets.QRadioButton(self.tab)
        self.avgButton.setObjectName("avgButton")
        self.gridLayout_4.addWidget(self.avgButton, 1, 0, 1, 1)
        self.KMeansButton = QtWidgets.QRadioButton(self.tab)
        self.KMeansButton.setObjectName("KMeansButton")
        self.gridLayout_4.addWidget(self.KMeansButton, 3, 1, 1, 1)
        self.histButton = QtWidgets.QRadioButton(self.tab)
        self.histButton.setObjectName("histButton")
        self.gridLayout_4.addWidget(self.histButton, 2, 1, 1, 1)
        self.lineButton = QtWidgets.QRadioButton(self.tab)
        self.lineButton.setObjectName("lineButton")
        self.gridLayout_4.addWidget(self.lineButton, 1, 1, 1, 1)
        self.analyzeTab.addTab(self.tab, "")
        self.predictTab = QtWidgets.QWidget()
        self.predictTab.setObjectName("predictTab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.predictTab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.autoSelectPredictButton = QtWidgets.QRadioButton(self.predictTab)
        self.autoSelectPredictButton.setObjectName("autoSelectPredictButton")
        self.gridLayout_3.addWidget(self.autoSelectPredictButton, 0, 0, 1, 1)
        self.radioButton_3 = QtWidgets.QRadioButton(self.predictTab)
        self.radioButton_3.setObjectName("radioButton_3")
        self.gridLayout_3.addWidget(self.radioButton_3, 1, 0, 1, 1)
        self.radioButton_2 = QtWidgets.QRadioButton(self.predictTab)
        self.radioButton_2.setObjectName("radioButton_2")
        self.gridLayout_3.addWidget(self.radioButton_2, 2, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.predictTab)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_3.addWidget(self.lineEdit, 4, 0, 1, 1)
        self.predictButton = QtWidgets.QPushButton(self.predictTab)
        self.predictButton.setObjectName("predictButton")
        self.gridLayout_3.addWidget(self.predictButton, 4, 1, 1, 1)
        self.trainButton = QtWidgets.QPushButton(self.predictTab)
        self.trainButton.setObjectName("trainButton")
        self.gridLayout_3.addWidget(self.trainButton, 3, 0, 1, 2)
        self.decisionTreeButton = QtWidgets.QRadioButton(self.predictTab)
        self.decisionTreeButton.setObjectName("decisionTreeButton")
        self.gridLayout_3.addWidget(self.decisionTreeButton, 0, 1, 1, 1)
        self.radioButton = QtWidgets.QRadioButton(self.predictTab)
        self.radioButton.setObjectName("radioButton")
        self.gridLayout_3.addWidget(self.radioButton, 1, 1, 1, 1)
        self.radioButton_5 = QtWidgets.QRadioButton(self.predictTab)
        self.radioButton_5.setObjectName("radioButton_5")
        self.gridLayout_3.addWidget(self.radioButton_5, 2, 1, 1, 1)
        self.analyzeTab.addTab(self.predictTab, "")
        self.seriesPredictTab = QtWidgets.QWidget()
        self.seriesPredictTab.setObjectName("seriesPredictTab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.seriesPredictTab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.autoSelectSeriesButton = QtWidgets.QRadioButton(self.seriesPredictTab)
        self.autoSelectSeriesButton.setObjectName("autoSelectSeriesButton")
        self.gridLayout_2.addWidget(self.autoSelectSeriesButton, 0, 0, 1, 1)
        self.LSTMButton = QtWidgets.QRadioButton(self.seriesPredictTab)
        self.LSTMButton.setObjectName("LSTMButton")
        self.gridLayout_2.addWidget(self.LSTMButton, 1, 0, 1, 1)
        self.GRUButton = QtWidgets.QRadioButton(self.seriesPredictTab)
        self.GRUButton.setObjectName("GRUButton")
        self.gridLayout_2.addWidget(self.GRUButton, 2, 0, 1, 1)
        self.prophetButton = QtWidgets.QRadioButton(self.seriesPredictTab)
        self.prophetButton.setObjectName("prophetButton")
        self.gridLayout_2.addWidget(self.prophetButton, 3, 0, 1, 1)
        self.seriesLineEdit = QtWidgets.QLineEdit(self.seriesPredictTab)
        self.seriesLineEdit.setObjectName("seriesLineEdit")
        self.gridLayout_2.addWidget(self.seriesLineEdit, 5, 0, 1, 1)
        self.predictSeriesButton = QtWidgets.QPushButton(self.seriesPredictTab)
        self.predictSeriesButton.setObjectName("predictSeriesButton")
        self.gridLayout_2.addWidget(self.predictSeriesButton, 5, 1, 1, 1)
        self.trainSeriesButton = QtWidgets.QPushButton(self.seriesPredictTab)
        self.trainSeriesButton.setObjectName("trainSeriesButton")
        self.gridLayout_2.addWidget(self.trainSeriesButton, 4, 0, 1, 2)
        self.analyzeTab.addTab(self.seriesPredictTab, "")
        self.gridLayout.addWidget(self.analyzeTab, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 705, 23))
        self.menubar.setObjectName("menubar")
        self.fileMenu = QtWidgets.QMenu(self.menubar)
        self.fileMenu.setObjectName("fileMenu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.importFromFileAction = QtWidgets.QAction(MainWindow)
        self.importFromFileAction.setObjectName("importFromFileAction")
        self.saveAsAction = QtWidgets.QAction(MainWindow)
        self.saveAsAction.setObjectName("saveAsAction")
        self.predictAction = QtWidgets.QAction(MainWindow)
        self.predictAction.setObjectName("predictAction")
        self.seriesPredictAction = QtWidgets.QAction(MainWindow)
        self.seriesPredictAction.setObjectName("seriesPredictAction")
        self.fileMenu.addAction(self.importFromFileAction)
        self.fileMenu.addAction(self.saveAsAction)
        self.menubar.addAction(self.fileMenu.menuAction())

        self.retranslateUi(MainWindow)
        self.analyzeTab.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "基于sklearn的轻量级数据分析预测软件V1.0"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">开始运算</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">正在训练模型...完成</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">模型准确率：94.24%</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">正在预测数据...完成</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">运算结束</p></body></html>"))
        self.plainTextEdit.setPlainText(_translate("MainWindow", "在此输入原数据"))
        self.computeButton.setText(_translate("MainWindow", "计算"))
        self.radioButton_4.setText(_translate("MainWindow", "方差"))
        self.avgButton.setText(_translate("MainWindow", "均值"))
        self.KMeansButton.setText(_translate("MainWindow", "聚类"))
        self.histButton.setText(_translate("MainWindow", "频率直方图"))
        self.lineButton.setText(_translate("MainWindow", "折线图"))
        self.analyzeTab.setTabText(self.analyzeTab.indexOf(self.tab), _translate("MainWindow", "数据分析"))
        self.autoSelectPredictButton.setText(_translate("MainWindow", "自动选择"))
        self.radioButton_3.setText(_translate("MainWindow", "神经网络"))
        self.radioButton_2.setText(_translate("MainWindow", "逻辑回归"))
        self.lineEdit.setText(_translate("MainWindow", "在此输入需预测数据"))
        self.predictButton.setText(_translate("MainWindow", "预测"))
        self.trainButton.setText(_translate("MainWindow", "训练"))
        self.decisionTreeButton.setText(_translate("MainWindow", "决策树"))
        self.radioButton.setText(_translate("MainWindow", "KNN"))
        self.radioButton_5.setText(_translate("MainWindow", "朴素贝叶斯"))
        self.analyzeTab.setTabText(self.analyzeTab.indexOf(self.predictTab), _translate("MainWindow", "预测"))
        self.autoSelectSeriesButton.setText(_translate("MainWindow", "自动选择"))
        self.LSTMButton.setText(_translate("MainWindow", "LSTM"))
        self.GRUButton.setText(_translate("MainWindow", "GRU"))
        self.prophetButton.setText(_translate("MainWindow", "Prophet"))
        self.seriesLineEdit.setText(_translate("MainWindow", "在此输入需预测时长"))
        self.predictSeriesButton.setText(_translate("MainWindow", "预测"))
        self.trainSeriesButton.setText(_translate("MainWindow", "训练"))
        self.analyzeTab.setTabText(self.analyzeTab.indexOf(self.seriesPredictTab), _translate("MainWindow", "序列预测"))
        self.fileMenu.setTitle(_translate("MainWindow", "文件"))
        self.importFromFileAction.setText(_translate("MainWindow", "导入"))
        self.saveAsAction.setText(_translate("MainWindow", "另存为"))
        self.predictAction.setText(_translate("MainWindow", "预测"))
        self.seriesPredictAction.setText(_translate("MainWindow", "序列预测"))

